/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra.models;

import hr.algebra.dal.RepositoryFactory;
import hr.algebra.dal.RepositoryMovie;
import hr.algebra.model.Movie;
import hr.algebra.model.MovieTable;
import hr.algebra.model.Person;
import hr.algebra.utils.FileUtils;
import hr.algebra.utils.IconUtils;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Komp
 */
public class UserMovieManager extends javax.swing.JPanel {

    RepositoryMovie repositoryMovie;
    MovieTable movieTable;

    private Movie selectedMovie;
    private Person selectedPerson;

    private DefaultListModel<Person> actorsModel;

    private Set<Person> actorsAdd;
    private Set<Person> actorsRemove;

    /**
     * Creates new form UserMovieManager
     */
    public UserMovieManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfOriginalTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPublishedDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDirector = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfDuration = new javax.swing.JTextField();
        tfGenre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsActors = new javax.swing.JList<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnChoose = new javax.swing.JButton();
        tfChoose = new javax.swing.JTextField();
        pnlMovies = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        btnDeleteActor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfActorFirstName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfActorLastName = new javax.swing.JTextField();
        btnAddNewActor = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Title:");

        jLabel2.setText("Original title:");

        jLabel3.setText("Description:");

        jLabel4.setText("Published date:");

        jLabel5.setText("Director:");

        jLabel6.setText("Duration:");

        jLabel7.setText("Genre:");

        jLabel8.setText("Actors:");

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        jScrollPane1.setViewportView(lsActors);

        btnSave.setBackground(java.awt.Color.green);
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(java.awt.Color.red);
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        tfChoose.setEditable(false);

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoviesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMoviesMouseReleased(evt);
            }
        });
        pnlMovies.setViewportView(tblMovies);

        btnDeleteActor.setBackground(java.awt.Color.red);
        btnDeleteActor.setText("X");
        btnDeleteActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActorActionPerformed(evt);
            }
        });

        jLabel9.setText("Actor first name:");

        jLabel10.setText("Actor last name:");

        btnAddNewActor.setBackground(java.awt.Color.green);
        btnAddNewActor.setText("Add");
        btnAddNewActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfOriginalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(tfActorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(tfActorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddNewActor))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDeleteActor)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(tfPublishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(138, 138, 138))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlMovies)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChoose)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPublishedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfOriginalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDeleteActor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(2, 2, 2)
                                .addComponent(tfActorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel10)
                                .addGap(2, 2, 2)
                                .addComponent(tfActorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddNewActor))))
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlMovies, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void tblMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviesMouseClicked
        try {
            initMovieSelect();
        } catch (IOException ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMoviesMouseClicked

    private void tblMoviesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviesMouseReleased
        try {
            initMovieSelect();
        } catch (IOException ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMoviesMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (selectedMovie.getPicturePath() != null) {
                Files.deleteIfExists(Paths.get(selectedMovie.getPicturePath()));
            }
            repositoryMovie.deletePerson(selectedMovie.getDirector().getId());
            repositoryMovie.deleteMovie(selectedMovie.getId());
            movieTable.setMovies(repositoryMovie.selectMovies());
            clearActor();
            clearForm();
        } catch (Exception ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        File file = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (file == null) {
            return;
        }
        tfChoose.setText(file.getAbsolutePath());
        setPicture(lblImage, file);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnDeleteActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActorActionPerformed
        selectedPerson = lsActors.getSelectedValue();
        actorsRemove.add(selectedPerson);
        actorsModel.removeElement(selectedPerson);
        selectedPerson = null;
    }//GEN-LAST:event_btnDeleteActorActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Movie movie = new Movie(
                    tfTitle.getText().trim(),
                    LocalDateTime.parse(tfPublishedDate.getText().trim(), Movie.DATE_FORMAT),
                    taDescription.getText().trim(),
                    tfOriginalTitle.getText().trim(),
                    getPerson(tfDirector.getText().trim()),
                    null,
                    tfDuration.getText().trim(),
                    tfGenre.getText().trim(),
                    selectedMovie.getPicturePath()
            );

            if (!tfChoose.equals("")) {
                movie.setPicturePath(tfChoose.getText().trim());
            }
            
            if (selectedMovie.getDirector() != movie.getDirector()) {
                movie.getDirector().setId(repositoryMovie.createPerson(movie.getDirector()));
            }
            repositoryMovie.updateMovie(selectedMovie.getId(), movie);

            for (Person person : actorsRemove) {
                repositoryMovie.deletePerson(person.getId());
            }

            movieTable.setMovies(repositoryMovie.selectMovies());
            clearForm();
            clearActor();
        } catch (Exception ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddNewActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActorActionPerformed
        if (tfActorFirstName.getText().equals("") || tfActorLastName.getText().equals("")) {
            return;
        }

        Person person = new Person(tfActorFirstName.getText().trim(), tfActorLastName.getText().trim());

        Optional<Person> existingPerson;
        try {

            existingPerson = repositoryMovie.selectPersonByName(person);

            if (existingPerson.isPresent()) {
                repositoryMovie.createMovieActor(existingPerson.get(), selectedMovie);                
            }
            else{
            int personID = repositoryMovie.createPerson(person);
            Person newPerson = new Person(personID, person.getFirstName(), person.getLastName());
            actorsModel.add(0, newPerson);
            lsActors.setModel(actorsModel);
            repositoryMovie.createMovieActor(newPerson, selectedMovie);
            }
   
            clearNewActorFields();
        } catch (Exception ex) {

        }


    }//GEN-LAST:event_btnAddNewActorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewActor;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteActor;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JList<Person> lsActors;
    private javax.swing.JScrollPane pnlMovies;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField tfActorFirstName;
    private javax.swing.JTextField tfActorLastName;
    private javax.swing.JTextField tfChoose;
    private javax.swing.JTextField tfDirector;
    private javax.swing.JTextField tfDuration;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfOriginalTitle;
    private javax.swing.JTextField tfPublishedDate;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables

    private void init() {

        try {
            initRepo();
            initTable();
            initActorsModel();
            initPersonModels();
        } catch (Exception ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void initRepo() throws Exception {
        repositoryMovie = RepositoryFactory.getMovieRepository();
    }

    private void initTable() throws Exception {
        movieTable = new MovieTable(repositoryMovie.selectMovies());
        tblMovies.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblMovies.setAutoCreateRowSorter(true);
        tblMovies.setRowHeight(20);
        tblMovies.setModel(movieTable);
    }

    private void initActorsModel() {
        actorsModel = new DefaultListModel<>();
        lsActors.setModel(actorsModel);
    }

    private void initPersonModels() {
        actorsAdd = new TreeSet<>();
        actorsRemove = new TreeSet<>();
    }

    private void initMovieSelect() throws IOException {
        clearPersons();
        displayMovie();
    }

    private void clearPersons() {
        actorsAdd.clear();
        actorsRemove.clear();
    }

    private void displayMovie() throws IOException {
        int selectedRow = tblMovies.getSelectedRow();
        int rowIndex = tblMovies.convertRowIndexToModel(selectedRow);

        int id = (int) movieTable.getValueAt(rowIndex, 0);

        Optional<Movie> optMovie;
        try {
            optMovie = repositoryMovie.selectMovie(id);
            if (optMovie.isPresent()) {
                selectedMovie = optMovie.get();
                fillForm(selectedMovie);
            }
        } catch (Exception ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillForm(Movie selectedMovie) throws IOException {
        tfTitle.setText(selectedMovie.getTitle());
        tfOriginalTitle.setText(selectedMovie.getOriginalTitle());
        taDescription.setText(selectedMovie.getDescription());
        tfDirector.setText(selectedMovie.getDirector().toString());
        tfPublishedDate.setText(selectedMovie.getPublishedDate().format(Movie.DATE_FORMAT));
        tfDuration.setText(selectedMovie.getDuration());
        tfGenre.setText(selectedMovie.getGenre());

        if (selectedMovie.getPicturePath() != null && Files.exists(Paths.get(selectedMovie.getPicturePath()))) {
            tfChoose.setText(selectedMovie.getPicturePath());
            lblImage.setIcon(IconUtils.createIcon(new File(selectedMovie.getPicturePath()), lblImage.getWidth(), lblImage.getHeight()));
        } else {
            lblImage.setIcon(null);
            tfChoose.setText("");
        }
        loadActors(selectedMovie);
    }

    private void loadActors(Movie selectedMovie) {
        actorsModel.clear();
        if (!selectedMovie.getActors().isEmpty()) {
            selectedMovie.getActors().forEach(actorsModel::addElement);
        }
        lsActors.setModel(actorsModel);
    }

    private void setPicture(JLabel lblImage, File file) {
        try {
            lblImage.setIcon(IconUtils.createIcon(file, lblImage.getWidth(), lblImage.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(UserMovieManager.class.getName()).log(Level.SEVERE, null, ex);
            lblImage.setIcon(null);
        }
    }

    private void clearActor() {
        actorsAdd.clear();
        actorsRemove.clear();
    }

    private void clearForm() {
        tfTitle.setText("");
        tfOriginalTitle.setText("");
        taDescription.setText("");
        tfPublishedDate.setText("");
        tfDirector.setText("");
        tfGenre.setText("");
        tfDuration.setText("");
        tfChoose.setText("");
        lblImage.setIcon(null);
        selectedPerson = null;

        actorsModel.clear();
        lsActors.setModel(actorsModel);
    }

    private Person getPerson(String data) {
        String[] personName = data.trim().split(" ", 2);
        switch (personName.length) {
            case 1:
                return new Person(personName[0], "");
            case 2:
                return new Person(personName[0], personName[1]);
        }
        return null;
    }

    private void clearNewActorFields() {
        tfActorFirstName.setText("");
        tfActorLastName.setText("");
    }

}
